name: MessageHider
version: 1.1
main: de.rapha149.messagehider.Main

commands:
  messagehider:
    description: MessageHider command for logging messages, creating empty filters or reloading the config.
    usage: /messagehider <log|create|reload>
    permission: messagehider
    aliases: [mh]

permissions:
  messagehider.log:
    description: Permission for '/messagehider log'.
    children:
      messagehider: true
  messagehider.create:
    description: Permission for '/messagehider create'.
    children:
      messagehider: true
  messagehider.reload:
    description: Permission for '/messagehider reload'.
    children:
      messagehider: true
