name: MessageHider
author: Rapha149
version: 1.8
main: de.rapha149.messagehider.Main
softdepend: [PlaceholderAPI]

commands:
  messagehider:
    description: MessageHider command for logging messages, creating empty filters or reloading the config.
    usage: /messagehider <reload|log|create|check|run>
    permission: messagehider
    aliases: [mh]

permissions:
  messagehider.reload:
    description: Permission for '/messagehider reload'.
    children:
      messagehider: true
  messagehider.log:
    description: Permission for '/messagehider log'.
    children:
      messagehider: true
  messagehider.create:
    description: Permission for '/messagehider create'.
    children:
      messagehider: true
  messagehider.createcommand:
    description: Permission for '/messagehider createcommand'.
    children:
      messagehider: true
  messagehider.check:
    description: Permission for '/messagehider check'.
    children:
      messagehider: true
  messagehider.run:
    description: Permission for '/messagehider run'.
    children:
      messagehider: true
